adapter_configs: {}
api_server:
    auth:
        allowed_ips: []
        api_keys: []
        enabled: false
        hmac_secret: ""
        jwt_secret: ""
        token_expiry: 3600
    cors:
        allow_credentials: false
        allowed_headers:
            - Content-Type
            - Authorization
            - X-API-Key
            - X-Requested-With
        allowed_methods:
            - GET
            - POST
            - PUT
            - DELETE
            - OPTIONS
        allowed_origins:
            - '*'
        enabled: true
        exposed_headers:
            - X-RateLimit-Limit
            - X-RateLimit-Remaining
            - X-RateLimit-Reset
        max_age: 86400
    enabled: true
    host: localhost
    idle_timeout: 120
    port: 8081
    rate_limit:
        burst_size: 10
        cleanup_interval: 300
        enabled: true
        requests_per_minute: 60
        window_size: 60
    read_timeout: 30
    security:
        content_type_options: true
        csp_directive: default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; connect-src 'self'
        csp_enabled: true
        frame_options: DENY
        hsts_enabled: true
        hsts_include_subdomains: true
        hsts_max_age: 31536000
        referrer_policy: strict-origin-when-cross-origin
        xss_protection: true
    tls_cert_file: ""
    tls_enabled: false
    tls_key_file: ""
    write_timeout: 30
database_path: ./bridge.db
device_id: ""
device_key: ""
enabled_adapters:
    - simulator
heartbeat_interval: 60
log_file: ""
log_level: info
queue_max_size: 10000
server_url: http://localhost:3000
tier: normal
unlock_duration: 3000
update_manifest_url: ""
update_public_key: ""
updates_enabled: true
