# Gym Door Bridge Configuration
# Device configuration (set during pairing process)
device_id: ""
device_key: ""

# Server configuration
server_url: "https://repset.onezy.in"

# Performance tier (auto-detected, can be overridden)
tier: "normal"

# Queue configuration
queue_max_size: 10000
heartbeat_interval: 60  # seconds

# Door control configuration
unlock_duration: 3000  # milliseconds

# Database configuration
database_path: "./bridge.db"

# Logging configuration
log_level: "info"  # debug, info, warn, error
log_file: ""       # empty for stdout only

# Adapter configuration
enabled_adapters:
  - "simulator"