name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release'
        required: true
        default: 'v1.0.0'

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        
    - name: Get version
      id: version
      run: |
        if ("${{ github.event_name }}" -eq "push") {
          $version = "${{ github.ref_name }}"
        } else {
          $version = "${{ github.event.inputs.version }}"
        }
        echo "VERSION=$version" >> $env:GITHUB_OUTPUT
        echo "Building version: $version"
      shell: powershell
      
    - name: Build executable
      run: |
        go mod tidy
        go build -ldflags "-s -w -X main.version=${{ steps.version.outputs.VERSION }}" -o gym-door-bridge.exe ./cmd
      shell: cmd
      
    - name: Create release package
      run: |
        mkdir release
        # Copy the main executable
        copy gym-door-bridge.exe release\
        
        # Copy the new installation scripts
        copy install-bridge.ps1 release\
        copy quick-install.ps1 release\
        
        # Copy documentation
        if exist README.md copy README.md release\
        if exist INSTALLATION_GUIDE.md copy INSTALLATION_GUIDE.md release\
        if exist docs\installation\gym-owner-guide.md copy docs\installation\gym-owner-guide.md release\
        
        # Create example config
        echo # RepSet Bridge Example Configuration > release\config.yaml.example
        echo server_url: "https://repset.onezy.in" >> release\config.yaml.example
        echo tier: "normal" >> release\config.yaml.example
        echo # Device credentials - filled during pairing >> release\config.yaml.example
        echo device_id: "" >> release\config.yaml.example
        echo device_key: "" >> release\config.yaml.example
        
        # Create the ZIP package with proper naming
        cd release
        powershell -Command "Compress-Archive -Path * -DestinationPath ..\gym-door-bridge-windows.zip"
        powershell -Command "Compress-Archive -Path * -DestinationPath ..\gym-door-bridge-${{ steps.version.outputs.VERSION }}-windows.zip"
      shell: cmd
      
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.version.outputs.VERSION }}
        name: Gym Door Bridge ${{ steps.version.outputs.VERSION }}
        body: |
          ## 🚀 Gym Door Bridge ${{ steps.version.outputs.VERSION }}
          
          ### For Gym Owners (Easy Installation)
          
          **Ultra-Fast One-Line Install (with pair code):**
          ```powershell
          # Run PowerShell as Administrator:
          Invoke-WebRequest -Uri "https://github.com/${{ github.repository }}/releases/latest/download/install-bridge.ps1" -OutFile "$env:TEMP\install-bridge.ps1"; & "$env:TEMP\install-bridge.ps1" -PairCode "YOUR_PAIR_CODE"
          ```
          
          **Quick Install (manual pairing):**
          ```powershell
          # Run PowerShell as Administrator:
          Invoke-WebRequest -Uri "https://github.com/${{ github.repository }}/releases/latest/download/quick-install.ps1" -OutFile "$env:TEMP\quick-install.ps1"; & "$env:TEMP\quick-install.ps1"
          ```
          
          **Manual Install:**
          1. Download `gym-door-bridge-windows.zip`
          2. Extract and run `install-bridge.ps1` as Administrator
          3. Pair with your gym platform using the provided code
          
          ### Features
          - ✅ Automatic biometric device discovery
          - ✅ Windows service installation
          - ✅ Support for ZKTeco, ESSL, Realtime devices
          - ✅ Real-time member check-in sync
          - ✅ Zero-configuration setup
          - ⭐ **NEW**: Smart pairing with automatic unpair/re-pair capability
          - ⭐ **NEW**: Enhanced error handling and recovery
          
          ### System Requirements
          - Windows 10/11 or Windows Server 2016+
          - Administrator privileges for installation
          - Network access to biometric devices
          
          See [Installation Guide](https://github.com/${{ github.repository }}/blob/main/INSTALLATION.md) for detailed instructions.
        files: |
          gym-door-bridge-windows.zip
          gym-door-bridge-${{ steps.version.outputs.VERSION }}-windows.zip
          gym-door-bridge.exe
          install-bridge.ps1
          quick-install.ps1
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}